/**
 * 与 receipt-details 一致的凭证详情页样式（入库/出库详情复用）
 * 样式布局保持，数据对象替换为 Inbound/Outbound 即可
 */
import { StyleSheet } from 'react-native';

export const voucherDetailStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#ECEFF1',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  scrollView: { flex: 1 },
  scrollContent: { padding: 12, paddingBottom: 100 },
  summaryCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 12,
    marginBottom: 12,
    flexDirection: 'row',
    alignItems: 'stretch',
  },
  imageContainer: { position: 'relative', marginRight: 12 },
  imagePlaceholder: {
    width: 80,
    height: 80,
    borderRadius: 8,
    backgroundColor: '#E9ECEF',
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
  },
  imagePlaceholderContent: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  receiptImage: { width: '100%', height: '100%' },
  summaryContent: { flex: 1, justifyContent: 'space-between' },
  summaryContentTop: { flex: 1, justifyContent: 'space-between' },
  summaryContentMain: { flex: 1 },
  submittedInfo: { alignSelf: 'flex-end', marginTop: 4 },
  submittedText: { fontSize: 11, color: '#95A5A6', textAlign: 'right' },
  storeName: {
    fontSize: 17,
    fontWeight: '600',
    color: '#2D3436',
    lineHeight: 22,
    height: 22,
    marginBottom: 2,
    borderBottomWidth: 1,
    borderBottomColor: 'transparent',
    paddingVertical: 0,
  },
  storeNameInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 22,
    marginBottom: 2,
  },
  storeNameInput: {
    flex: 1,
    fontSize: 17,
    fontWeight: '600',
    color: '#2D3436',
    lineHeight: 22,
    borderBottomWidth: 1,
    borderBottomColor: '#6C5CE7',
    height: 22,
    paddingVertical: 0,
    paddingRight: 4,
    transform: [{ translateY: -1 }],
  },
  storeNameDropdownIcon: {
    paddingLeft: 4,
    justifyContent: 'center',
    alignItems: 'center',
    height: 22,
  },
  amountRow: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'baseline',
    marginTop: 2,
  },
  amountContainer: { flexDirection: 'row', alignItems: 'baseline', flexWrap: 'wrap' },
  totalAmount: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#6C5CE7',
    marginRight: 8,
    lineHeight: 28,
  },
  dateContainer: { marginTop: 8, height: 24 },
  dateTouchable: { alignSelf: 'flex-start' },
  date: {
    fontSize: 14,
    fontWeight: '600',
    color: '#636E72',
    lineHeight: 18,
    marginTop: 2,
    marginLeft: 11,
    marginBottom: 0,
  },
  dateText: { fontSize: 14, color: '#636E72', lineHeight: 18, fontWeight: '600' },
  dateTag: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 1,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#6C5CE7',
    backgroundColor: '#F8F9FA',
    height: 20,
  },
  paymentCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    paddingVertical: 2,
    paddingHorizontal: 12,
    marginBottom: 8,
  },
  paymentRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  cardLabel: { fontSize: 14, color: '#636E72', marginRight: 12, fontWeight: '500' },
  cardValue: {
    fontSize: 14,
    color: '#2D3436',
    fontWeight: '500',
    paddingVertical: 10,
    lineHeight: 20,
    marginRight: 37,
  },
  accountTouchable: { flex: 1, alignItems: 'flex-end', justifyContent: 'center', minHeight: 40 },
  accountTag: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8F9FA',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#6C5CE7',
    maxWidth: 250,
    minWidth: 120,
    flexShrink: 0,
  },
  accountText: {
    fontSize: 14,
    color: '#2D3436',
    fontWeight: '500',
    flexShrink: 1,
    marginRight: 6,
    maxWidth: 200,
    lineHeight: 20,
  },
  tagIcon: { marginLeft: 4, opacity: 0.8, flexShrink: 0 },
  itemsSection: {
    marginBottom: 12,
    backgroundColor: '#fff',
    borderRadius: 10,
    overflow: 'hidden',
  },
  sectionTitleContainer: {
    paddingHorizontal: 8,
    paddingTop: 8,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#E9ECEF',
  },
  sectionTitle: { fontSize: 17, fontWeight: '600', color: '#2D3436' },
  itemCard: {
    backgroundColor: '#fff',
    borderRadius: 0,
    paddingLeft: 8,
    paddingTop: 4,
    paddingBottom: 4,
    paddingRight: 32,
    marginBottom: 0,
  },
  itemCardWithBorder: { borderBottomWidth: 1, borderBottomColor: '#E9ECEF' },
  deleteItemButton: {
    position: 'absolute',
    top: '50%',
    marginTop: -14,
    right: 0,
    zIndex: 1,
    padding: 4,
  },
  itemHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 1,
  },
  itemName: {
    flex: 1,
    fontSize: 15,
    fontWeight: '600',
    color: '#2D3436',
    marginRight: 6,
    lineHeight: 20,
    height: 20,
    borderBottomWidth: 1,
    borderBottomColor: 'transparent',
    paddingVertical: 0,
    transform: [{ translateY: -2 }],
  },
  itemNameInput: {
    flex: 1,
    fontSize: 15,
    fontWeight: '600',
    color: '#2D3436',
    borderBottomWidth: 1,
    borderBottomColor: '#6C5CE7',
    lineHeight: 20,
    height: 20,
    paddingVertical: 0,
    marginRight: 6,
    transform: [{ translateY: -4 }],
  },
  itemQuantity: {
    fontSize: 16,
    fontWeight: '600',
    color: '#6C5CE7',
    paddingVertical: 4,
    paddingHorizontal: 7,
    minWidth: 70,
    textAlign: 'right',
    lineHeight: 20,
  },
  quantityInput: {
    fontSize: 16,
    fontWeight: '600',
    color: '#6C5CE7',
    borderWidth: 1,
    borderColor: '#6C5CE7',
    borderRadius: 4,
    paddingVertical: 3,
    paddingHorizontal: 6,
    minWidth: 70,
    textAlign: 'right',
    lineHeight: 20,
  },
  itemTags: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    marginTop: 0,
    position: 'relative',
  },
  tagGroupLeft: { width: 120, alignItems: 'flex-start' },
  tagGroupCenter: { marginLeft: 2, alignItems: 'flex-start' },
  tagGroupRight: { flex: 1, alignItems: 'flex-end' },
  tag: {
    paddingLeft: 10,
    paddingRight: 5,
    paddingVertical: 4,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    maxWidth: 140,
    backgroundColor: '#95A5A6',
  },
  tagText: { color: '#fff', fontSize: 11, fontWeight: '600', flexShrink: 1 },
  tagTouchable: {
    paddingLeft: 10,
    paddingRight: 5,
    paddingVertical: 4,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    maxWidth: 140,
    backgroundColor: '#6C5CE7',
  },
  unitTag: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    backgroundColor: '#F0F0F0',
  },
  unitTagText: { fontSize: 11, fontWeight: '500', color: '#636E72' },
  unitInput: {
    fontSize: 11,
    fontWeight: '500',
    color: '#636E72',
    borderWidth: 1,
    borderColor: '#6C5CE7',
    borderRadius: 4,
    paddingVertical: 2,
    paddingHorizontal: 6,
    minWidth: 50,
    textAlign: 'right',
  },
  addItemButtonContainer: {
    paddingTop: 12,
    paddingBottom: 4,
    backgroundColor: '#ECEFF1',
    alignItems: 'center',
  },
  addItemButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F8F9FA',
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: '#CED4DA',
    alignSelf: 'stretch',
  },
  addItemText: { marginLeft: 8, fontSize: 16, color: '#6C5CE7', fontWeight: '600' },
  bottomBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'transparent',
    paddingHorizontal: 16,
    paddingBottom: 16,
    paddingTop: 8,
    borderTopWidth: 0,
    flexDirection: 'row',
    gap: 12,
  },
  cancelButton: {
    flex: 1,
    backgroundColor: '#DDE2E6',
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.22,
    shadowRadius: 6,
    elevation: 6,
  },
  cancelButtonText: { fontSize: 16, color: '#636E72', fontWeight: '600' },
  confirmButton: {
    flex: 1,
    backgroundColor: '#6C5CE7',
    borderRadius: 12,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.22,
    shadowRadius: 6,
    elevation: 6,
  },
  confirmButtonText: { marginLeft: 8, fontSize: 16, color: '#fff', fontWeight: '600' },
  fab: {
    position: 'absolute',
    right: 20,
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#6C5CE7',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.22,
    shadowRadius: 6,
    elevation: 6,
  },
  editFab: { bottom: 20, backgroundColor: '#95A5A6' },
  errorText: { textAlign: 'center', marginTop: 50, fontSize: 16, color: '#E74C3C' },
  modalContainer: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.9)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalCloseButton: {
    position: 'absolute',
    top: 50,
    right: 20,
    zIndex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    borderRadius: 20,
    padding: 8,
  },
  modalImage: { width: '100%', height: '100%' },
  pickerOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'flex-end' },
  pickerBottomSheet: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingTop: 12,
    paddingBottom: 32,
    paddingHorizontal: 20,
    maxHeight: '70%',
  },
  pickerHandle: {
    width: 40,
    height: 4,
    backgroundColor: '#BDC3C7',
    borderRadius: 2,
    alignSelf: 'center',
    marginBottom: 16,
  },
  pickerHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 },
  pickerTitle: { fontSize: 18, fontWeight: '600', color: '#2D3436', flex: 1 },
  pickerCloseButton: { paddingHorizontal: 12, paddingVertical: 6 },
  pickerCloseText: { fontSize: 16, color: '#6C5CE7', fontWeight: '600' },
  pickerScrollView: { maxHeight: 400 },
  pickerOption: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    marginBottom: 8,
    backgroundColor: '#F8F9FA',
    minHeight: 48,
  },
  pickerOptionSelected: { backgroundColor: '#E8F4FD' },
  pickerColorIndicator: { width: 20, height: 20, borderRadius: 10, marginRight: 12 },
  pickerOptionText: { flex: 1, fontSize: 16, color: '#2D3436', fontWeight: '500' },
  pickerOptionTextSelected: { color: '#6C5CE7', fontWeight: '600' },
  datePickerIOS: { width: '100%', height: 200 },
  audioPlayButton: {
    position: 'absolute',
    bottom: 4,
    right: 4,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  audioPlayButtonActive: { backgroundColor: '#6C5CE7' },
  // 三选项替换弹窗（与 receipt-details / invoice-details 一致）
  duplicateModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  duplicateModalContentContainer: { width: '100%', maxWidth: 400, alignItems: 'center' },
  duplicateModalContent: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 24,
    width: '100%',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
  },
  duplicateModalHeader: { alignItems: 'center', marginBottom: 16 },
  duplicateModalTitle: { fontSize: 22, fontWeight: '600', color: '#2D3436', marginTop: 12, marginBottom: 0 },
  duplicateModalMessageBlock: { marginBottom: 24, paddingHorizontal: 8, alignItems: 'center', width: '100%' },
  duplicateModalNameContainer: {
    marginTop: 8,
    marginBottom: 20,
    alignSelf: 'stretch',
    borderBottomWidth: 1,
    borderBottomColor: '#E0E7FF',
    paddingBottom: 8,
  },
  duplicateModalNameText: {
    fontSize: 18,
    fontWeight: '800',
    color: '#6C5CE7',
    textAlign: 'center',
    letterSpacing: 0.3,
  },
  duplicateModalButtons: { flexDirection: 'column', width: '100%', gap: 10 },
  duplicateModalButton: {
    width: '100%',
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 52,
    flexDirection: 'row',
  },
  duplicateModalButtonReplace: {
    backgroundColor: '#27AE60',
    shadowColor: '#27AE60',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  duplicateModalButtonReplaceText: { fontSize: 17, fontWeight: '700', color: '#fff', letterSpacing: 0.5 },
  duplicateModalButtonMerge: { backgroundColor: '#FFF5F5', borderWidth: 2, borderColor: '#E74C3C' },
  duplicateModalButtonMergeText: { fontSize: 16, fontWeight: '600', color: '#E74C3C' },
  duplicateModalButtonDontChange: { backgroundColor: '#F8F9FA', borderWidth: 1, borderColor: '#E9ECEF' },
  duplicateModalButtonDontChangeText: { fontSize: 15, fontWeight: '500', color: '#95A5A6' },
});
