/**
 * 与 receipt 列表页一致的凭证列表样式（入库/出库列表复用）
 * 样式布局保持，数据对象替换为 Inbound/Outbound 即可
 */
import { StyleSheet } from 'react-native';

export const voucherListStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#ECEFF1',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#ECEFF1',
  },
  header: {
    backgroundColor: '#fff',
    paddingTop: 10,
    paddingBottom: 10,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#E9ECEF',
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  cancelButton: { paddingHorizontal: 12, paddingVertical: 8 },
  cancelButtonText: { fontSize: 14, color: '#6C5CE7', fontWeight: '500' },
  selectedCountContainer: { flex: 1, alignItems: 'center' },
  selectedCountText: { fontSize: 14, color: '#636E72', fontWeight: '500' },
  deleteButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 8,
    gap: 6,
  },
  deleteButtonText: { fontSize: 14, color: '#E74C3C', fontWeight: '600' },
  filterButton: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 12, paddingVertical: 8 },
  filterText: { fontSize: 14, color: '#636E72', marginRight: 4, fontWeight: '500' },
  sortButton: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 12, paddingVertical: 8 },
  sortText: { fontSize: 14, color: '#636E72', marginRight: 4, fontWeight: '500' },
  searchContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8F9FA',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: '#E9ECEF',
  },
  searchIcon: { marginRight: 8 },
  searchInput: { flex: 1, fontSize: 14, color: '#2D3436', padding: 0 },
  countText: { fontSize: 14, color: '#636E72', fontWeight: '500', minWidth: 30, textAlign: 'right' },
  receiptItem: {
    backgroundColor: '#fff',
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#E9ECEF',
    flexDirection: 'row',
    alignItems: 'center',
  },
  receiptItemSelected: { backgroundColor: '#E8F4FD' },
  checkboxContainer: { marginRight: 12 },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#BDC3C7',
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkboxSelected: { backgroundColor: '#6C5CE7', borderColor: '#6C5CE7' },
  receiptContent: { flex: 1 },
  firstRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  storeName: {
    flex: 1,
    fontSize: 16,
    fontWeight: '600',
    color: '#2D3436',
    marginRight: 12,
  },
  statusBadge: { paddingHorizontal: 12, paddingVertical: 4, borderRadius: 12 },
  statusText: { color: '#fff', fontSize: 12, fontWeight: '600' },
  confirmedStatusContainer: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  confirmedBadge: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#00B894',
    justifyContent: 'center',
    alignItems: 'center',
  },
  confirmedByText: { fontSize: 12, color: '#636E72', fontWeight: '500' },
  secondRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  amount: { fontSize: 16, fontWeight: '600', color: '#6C5CE7' },
  date: { fontSize: 14, color: '#636E72' },
  createdDate: { fontSize: 14, color: '#636E72', marginLeft: 'auto' },
  fabContainer: { position: 'absolute', right: 20, bottom: 20, alignItems: 'flex-end' },
  fabActionsContainer: { alignItems: 'flex-end' },
  fabMain: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#6C5CE7',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.22,
    shadowRadius: 6,
    elevation: 6,
  },
  fabAction: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.18,
    shadowRadius: 4,
    elevation: 4,
  },
  emptyContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', paddingVertical: 100 },
  emptyList: { flexGrow: 1 },
  sectionHeader: {
    backgroundColor: '#F8F9FA',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#E9ECEF',
  },
  sectionHeaderContent: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  sectionTitle: { fontSize: 16, fontWeight: '600', color: '#2D3436' },
  sectionHeaderRight: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  sectionCount: { fontSize: 14, color: '#636E72' },
  sectionAmount: { fontSize: 14, fontWeight: '600', color: '#6C5CE7' },
  listContent: { paddingHorizontal: 4, paddingTop: 4, paddingBottom: 100 },
  emptyText: { fontSize: 18, color: '#636E72', marginTop: 16, fontWeight: '600' },
  emptySubtext: { fontSize: 14, color: '#95A5A6', marginTop: 8 },
  filterBadge: { fontSize: 14, color: '#6C5CE7', fontWeight: '600' },
  pickerOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'flex-end' },
  pickerBottomSheet: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingTop: 12,
    paddingBottom: 32,
    paddingHorizontal: 20,
    maxHeight: '70%',
  },
  pickerHandle: {
    width: 40,
    height: 4,
    backgroundColor: '#BDC3C7',
    borderRadius: 2,
    alignSelf: 'center',
    marginBottom: 16,
  },
  pickerHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 },
  pickerHeaderRight: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  pickerTitle: { fontSize: 18, fontWeight: '600', color: '#2D3436', flex: 1 },
  pickerCloseButton: { paddingHorizontal: 12, paddingVertical: 6 },
  pickerCloseText: { fontSize: 16, color: '#6C5CE7', fontWeight: '600' },
  filterMainOptionLeft: { flexDirection: 'row', alignItems: 'center', flex: 1, gap: 12 },
  filterMainOptionRight: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  filterOptionLeft: { flexDirection: 'row', alignItems: 'center', flex: 1, gap: 12 },
  filterCheckbox: {
    width: 20,
    height: 20,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: '#BDC3C7',
    justifyContent: 'center',
    alignItems: 'center',
  },
  filterCheckboxSelected: { backgroundColor: '#6C5CE7', borderColor: '#6C5CE7' },
  pickerScrollView: { maxHeight: 400 },
  pickerOption: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    marginBottom: 8,
    backgroundColor: '#F8F9FA',
    minHeight: 48,
    gap: 12,
  },
  pickerOptionSelected: { backgroundColor: '#E8F4FD' },
  pickerOptionText: { flex: 1, fontSize: 16, color: '#2D3436', fontWeight: '500' },
  pickerOptionTextSelected: { color: '#6C5CE7', fontWeight: '600' },
  pickerBackButton: { paddingHorizontal: 12, paddingVertical: 6 },
  clearFilterButton: { paddingHorizontal: 12, paddingVertical: 6 },
  clearFilterText: { fontSize: 14, color: '#E74C3C', fontWeight: '500' },
  filterMainOption: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 16,
    paddingHorizontal: 16,
    borderRadius: 8,
    marginBottom: 8,
    backgroundColor: '#F8F9FA',
    minHeight: 56,
  },
  filterMainOptionText: { fontSize: 16, color: '#2D3436', fontWeight: '500', flex: 1 },
  filterCountBadge: {
    fontSize: 14,
    color: '#6C5CE7',
    fontWeight: '600',
    backgroundColor: '#E8F4FD',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
    minWidth: 24,
    textAlign: 'center',
  },
  successModalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'center', alignItems: 'center', padding: 20 },
  successModalContent: {
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 32,
    alignItems: 'center',
    width: '100%',
    maxWidth: 400,
  },
  successIconContainer: { marginBottom: 24 },
  successTitle: { fontSize: 28, fontWeight: 'bold', color: '#2D3436', marginBottom: 8 },
  successSubtitle: { fontSize: 16, color: '#636E72', marginBottom: 32 },
  successButtons: { width: '100%', gap: 12 },
  successButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 16,
    borderWidth: 2,
    borderColor: '#6C5CE7',
    gap: 12,
  },
  successButtonText: { fontSize: 16, fontWeight: '600', color: '#6C5CE7' },
});
