import { StyleSheet } from 'react-native';

export const confirmDialogStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  contentContainer: { width: '100%', maxWidth: 400, alignItems: 'center' },
  content: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 24,
    width: '100%',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
  },
  header: { alignItems: 'center', marginBottom: 16 },
  title: { fontSize: 22, fontWeight: '600', color: '#2D3436', textAlign: 'center' },
  messageBlock: { marginBottom: 24, paddingHorizontal: 8, alignItems: 'center', width: '100%' },
  messageText: { fontSize: 16, color: '#636E72', textAlign: 'center', lineHeight: 24 },
  buttons: { flexDirection: 'column', width: '100%', gap: 10 },
  button: {
    width: '100%',
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 52,
    flexDirection: 'row',
  },
  buttonPrimary: {
    backgroundColor: '#27AE60',
    shadowColor: '#27AE60',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  buttonPrimaryText: { fontSize: 17, fontWeight: '700', color: '#fff', letterSpacing: 0.5 },
  buttonDestructive: { backgroundColor: '#FFF5F5', borderWidth: 2, borderColor: '#E74C3C' },
  buttonDestructiveText: { fontSize: 16, fontWeight: '600', color: '#E74C3C' },
  buttonCancel: { backgroundColor: '#F8F9FA', borderWidth: 1, borderColor: '#E9ECEF' },
  buttonCancelText: { fontSize: 15, fontWeight: '500', color: '#95A5A6' },
});
